{
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
  "packages": {
    ".": {
      "release-type": "python"
    },
    "client": {
      "release-type": "node",
      "path": "client"
    }
  }
}
