site_name: AEGIS Docs
docs_dir: docs
site_dir: aegis-documentation

nav:
  - Home: index.md
  - Getting Started:
      - getting-started.md
      - Installation: getting-started/installation.md
      - Aegis System: getting-started/aegis-system.md
      - Agents: getting-started/agents.md
      - Client: getting-started/client.md
      - Running Aegis: getting-started/running-aegis.md
  - API Documentation:
      - api.md
      - Common:
          - AgentID: api/common/agent-id.md
          - AgentIDList: api/common/agent-id-list.md
          - Direction: api/common/direction.md
          - Location: api/common/location.md
          - LifeSignals: api/common/life-signals.md
      - World:
          - World: api/world/world.md
          - Grid: api/world/grid.md
          - WorldObjects:
              - WorldObject: api/world/objects/world-object.md
              - Survivor: api/world/objects/survivor.md
              - SurvivorGroup: api/world/objects/survivor-group.md
              - Rubble: api/world/objects/rubble.md
              - NoLayers: api/world/objects/no-layers.md
          - WorldObjectsInfo:
              - WorldObjectInfo: api/world/info/world-object-info.md
              - SurvivorInfo: api/world/info/survivor-info.md
              - SurvivorGroupInfo: api/world/info/survivor-group-info.md
              - RubbleInfo: api/world/info/rubble-info.md
              - NoLayersInfo: api/world/info/no-layers-info.md
              - GridInfo: api/world/info/grid-info.md
              - SurroundInfo: api/world/info/surround-info.md
      - Commands:
          - Agent Commands:
              - AgentCommand: api/agent_commands/agent-command.md
              - AgentUnknown: api/agent_commands/agent-unknown.md
              - Connect: api/agent_commands/connect.md
              - EndTurn: api/agent_commands/end-turn.md
              - Move: api/agent_commands/move.md
              - Observe: api/agent_commands/observe.md
              - SaveSurv: api/agent_commands/save-surv.md
              - SendMessage: api/agent_commands/send-message.md
              - Sleep: api/agent_commands/sleep.md
              - TeamDig: api/agent_commands/team-dig.md
          - Aegis Commands:
              - AegisUnknown: api/aegis_commands/aegis-unknown.md
              - CmdResultStart: api/aegis_commands/cmd-result-start.md
              - CmdResultEnd: api/aegis_commands/cmd-result-end.md
              - ConnectOK: api/aegis_commands/connect-ok.md
              - DeathCard: api/aegis_commands/death-card.md
              - Disconnect: api/aegis_commands/disconnect.md
              - FwdMessage: api/aegis_commands/fwd-message.md
              - MessagesStart: api/aegis_commands/messages-start.md
              - MessagesEnd: api/aegis_commands/messages-end.md
              - MoveResult: api/aegis_commands/move-result.md
              - ObserveResult: api/aegis_commands/observe-result.md
              - RoundStart: api/aegis_commands/round-start.md
              - RoundEnd: api/aegis_commands/round-end.md
              - SaveSurvResult: api/aegis_commands/save-surv-result.md
              - SleepResult: api/aegis_commands/sleep-result.md
              - TeamDigResult: api/aegis_commands/team-dig-result.md
      - Agent:
          - BaseAgent: api/agent/base-agent.md
          - AgentStates: api/agent/agent-states.md
          - LogLevels: api/agent/log-levels.md
  - Assignment 1 Config: a1_config.md
  - Common Errors: common_errors.md

theme:
  name: "material"
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: light blue
  font:
    text: Varela Round
  logo: assets/logo.png
  favicon: assets/favicon.png

plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src/]
          options:
            docstring_options:
              ignore_init_summary: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            merge_init_into_class: true
            show_source: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
