# This is the configuration file for all AEGIS system features.

# General aegis features
features:
  ENABLE_PREDICTIONS: true
  ENABLE_VARIABLE_AGENT_AMOUNT: false
  DEFAULT_AGENT_AMOUNT: 1

# Settings more specific to assignments, usually only assignments will decide to enable these
assignment_specific:
  ENABLE_MOVE_COST: false

# Settings more specific to competitions, usually only competitions will decide to enable these
competition_specific:
  VERSUS_MODE: false

# Client-specific configuration
client:
  CONFIG_TYPE: "assignment" # "assignment" or "competition"
