# pyright: reportUnusedParameter = false
# pyright: reportUnusedImport = false
# flake8: noqa F401

from . import AgentCommand, World, Location, MOVE, SAVE_SURV, Direction, Survivor


def send(command: AgentCommand) -> None: ...
def get_round_number() -> int: ...
def get_world() -> World | None: ...
def get_location() -> Location: ...
def log(message: str) -> None: ...
