# pyright: reportUnusedParameter = false
# pyright: reportUnusedImport = false
# flake8: noqa F401

from . import (
    AgentCommand,
    World,
    Location,
    MOVE,
    SAVE_SURV,
    Direction,
    Survivor,
    AgentID,
    Cell,
)


def get_round_number() -> int: ...
def get_agent_id() -> AgentID: ...
def get_location() -> Location: ...
def get_energy_level() -> int: ...
def send(command: AgentCommand) -> None: ...
def on_map(loc: Location) -> bool: ...
def get_cell_at(loc: Location) -> Cell | None: ...
def get_survs() -> list[Location]: ...
def get_energy_cells() -> list[Location]: ...
def log(message: str) -> None: ...
