"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Location(google.protobuf.message.Message):
    """Basic types"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.int
    y: builtins.int
    def __init__(
        self,
        *,
        x: builtins.int = ...,
        y: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["x", b"x", "y", b"y"]) -> None: ...

global___Location = Location

@typing.final
class AgentID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    GID_FIELD_NUMBER: builtins.int
    id: builtins.int
    gid: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        gid: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gid", b"gid", "id", b"id"]) -> None: ...

global___AgentID = AgentID

@typing.final
class Survivor(google.protobuf.message.Message):
    """World objects"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    id: builtins.int
    state: builtins.int
    """0 = alive, 1 = dead"""
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        state: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "state", b"state"]) -> None: ...

global___Survivor = Survivor

@typing.final
class Rubble(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MOVE_COST_FIELD_NUMBER: builtins.int
    move_cost: builtins.int
    def __init__(
        self,
        *,
        move_cost: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["move_cost", b"move_cost"]) -> None: ...

global___Rubble = Rubble

@typing.final
class Cell(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCATION_FIELD_NUMBER: builtins.int
    MOVE_COST_FIELD_NUMBER: builtins.int
    AGENT_IDS_FIELD_NUMBER: builtins.int
    HAS_SURVIVORS_FIELD_NUMBER: builtins.int
    SURVIVOR_FIELD_NUMBER: builtins.int
    RUBBLE_FIELD_NUMBER: builtins.int
    move_cost: builtins.int
    has_survivors: builtins.bool
    @property
    def location(self) -> global___Location: ...
    @property
    def agent_ids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AgentID]: ...
    @property
    def survivor(self) -> global___Survivor: ...
    @property
    def rubble(self) -> global___Rubble: ...
    def __init__(
        self,
        *,
        location: global___Location | None = ...,
        move_cost: builtins.int = ...,
        agent_ids: collections.abc.Iterable[global___AgentID] | None = ...,
        has_survivors: builtins.bool = ...,
        survivor: global___Survivor | None = ...,
        rubble: global___Rubble | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["location", b"location", "rubble", b"rubble", "survivor", b"survivor", "top_layer", b"top_layer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["agent_ids", b"agent_ids", "has_survivors", b"has_survivors", "location", b"location", "move_cost", b"move_cost", "rubble", b"rubble", "survivor", b"survivor", "top_layer", b"top_layer"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["top_layer", b"top_layer"]) -> typing.Literal["survivor", "rubble"] | None: ...

global___Cell = Cell

@typing.final
class WorldState(google.protobuf.message.Message):
    """World state"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    CELLS_FIELD_NUMBER: builtins.int
    AGENTS_FIELD_NUMBER: builtins.int
    SURVIVORS_FIELD_NUMBER: builtins.int
    width: builtins.int
    height: builtins.int
    @property
    def cells(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Cell]: ...
    @property
    def agents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Agent]: ...
    @property
    def survivors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Survivor]: ...
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        cells: collections.abc.Iterable[global___Cell] | None = ...,
        agents: collections.abc.Iterable[global___Agent] | None = ...,
        survivors: collections.abc.Iterable[global___Survivor] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agents", b"agents", "cells", b"cells", "height", b"height", "survivors", b"survivors", "width", b"width"]) -> None: ...

global___WorldState = WorldState

@typing.final
class Agent(google.protobuf.message.Message):
    """Agent information"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENT_ID_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    ENERGY_LEVEL_FIELD_NUMBER: builtins.int
    STEPS_TAKEN_FIELD_NUMBER: builtins.int
    energy_level: builtins.int
    steps_taken: builtins.int
    @property
    def agent_id(self) -> global___AgentID: ...
    @property
    def location(self) -> global___Location: ...
    def __init__(
        self,
        *,
        agent_id: global___AgentID | None = ...,
        location: global___Location | None = ...,
        energy_level: builtins.int = ...,
        steps_taken: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["agent_id", b"agent_id", "location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["agent_id", b"agent_id", "energy_level", b"energy_level", "location", b"location", "steps_taken", b"steps_taken"]) -> None: ...

global___Agent = Agent

@typing.final
class GroupData(google.protobuf.message.Message):
    """Group data for scoring"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    NUMBER_SAVED_FIELD_NUMBER: builtins.int
    NUMBER_PREDICTED_RIGHT_FIELD_NUMBER: builtins.int
    NUMBER_PREDICTED_WRONG_FIELD_NUMBER: builtins.int
    gid: builtins.int
    name: builtins.str
    score: builtins.int
    number_saved: builtins.int
    number_predicted_right: builtins.int
    number_predicted_wrong: builtins.int
    def __init__(
        self,
        *,
        gid: builtins.int = ...,
        name: builtins.str = ...,
        score: builtins.int = ...,
        number_saved: builtins.int = ...,
        number_predicted_right: builtins.int = ...,
        number_predicted_wrong: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["gid", b"gid", "name", b"name", "number_predicted_right", b"number_predicted_right", "number_predicted_wrong", b"number_predicted_wrong", "number_saved", b"number_saved", "score", b"score"]) -> None: ...

global___GroupData = GroupData

@typing.final
class RoundUpdate(google.protobuf.message.Message):
    """Round update"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROUND_FIELD_NUMBER: builtins.int
    WORLD_FIELD_NUMBER: builtins.int
    GROUPS_FIELD_NUMBER: builtins.int
    round: builtins.int
    @property
    def world(self) -> global___WorldState: ...
    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GroupData]: ...
    def __init__(
        self,
        *,
        round: builtins.int = ...,
        world: global___WorldState | None = ...,
        groups: collections.abc.Iterable[global___GroupData] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["world", b"world"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["groups", b"groups", "round", b"round", "world", b"world"]) -> None: ...

global___RoundUpdate = RoundUpdate

@typing.final
class SimulationComplete(google.protobuf.message.Message):
    """Simulation events
    Empty message for completion event
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SimulationComplete = SimulationComplete

@typing.final
class SimulationEvent(google.protobuf.message.Message):
    """Main event wrapper"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORLD_INIT_FIELD_NUMBER: builtins.int
    ROUND_UPDATE_FIELD_NUMBER: builtins.int
    COMPLETE_FIELD_NUMBER: builtins.int
    @property
    def world_init(self) -> global___WorldState: ...
    @property
    def round_update(self) -> global___RoundUpdate: ...
    @property
    def complete(self) -> global___SimulationComplete: ...
    def __init__(
        self,
        *,
        world_init: global___WorldState | None = ...,
        round_update: global___RoundUpdate | None = ...,
        complete: global___SimulationComplete | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["complete", b"complete", "event", b"event", "round_update", b"round_update", "world_init", b"world_init"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["complete", b"complete", "event", b"event", "round_update", b"round_update", "world_init", b"world_init"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["event", b"event"]) -> typing.Literal["world_init", "round_update", "complete"] | None: ...

global___SimulationEvent = SimulationEvent
