name: Build Client

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "macos-latest"
            platform: "mac"
          - os: "ubuntu-latest"
            platform: "linux"
          - os: "windows-latest"
            platform: "win"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build app
        run: npm run build:pack
        working-directory: ./client

      - name: Zip Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: 7z a packed-client/linux-client.zip packed-client/*.AppImage
        working-directory: ./client

      - name: Zip Mac
        if: startsWith(matrix.os, 'macos')
        run: 7z a packed-client/mac-client.zip packed-client/mac-universal/*.app
        working-directory: ./client

      - name: Zip Windows
        if: startsWith(matrix.os, 'windows')
        run: 7z a packed-client/win-client.zip packed-client/*.exe
        working-directory: ./client

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-client
          path: |
            ./client/packed-client/*.zip
