name: Build and Deploy Documentation

on:
  push:
    tags:
      - "v*-docs"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material "mkdocstrings[python]"

      - name: Build Documentations
        run: mkdocs build
        working-directory: ./src

      - name: Deploy to Gihub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./aegis-documentation
